# Application Configuration
spring:
  application:
    name: Automation Scheduler

  # Database Configuration (H2)
  datasource:
    url: jdbc:h2:file:./data/automation
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # Thymeleaf
  thymeleaf:
    cache: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

# Server Configuration
server:
  port: 8080

# SSH Execution Configuration
ssh:
  execution:
    max-concurrent-connections: 10
    connection-timeout: 30000
    execution-timeout: 30000
    use-virtual-threads: true

automation:
  screenshot:
    path: ./screenshots
  driver:
    headless: false
    timeout: 30

# Logging
logging:
  level:
    igsl.group.sshexecutor: DEBUG
    org.springframework.web: INFO
    org.openqa.selenium.devtools: OFF
    org.openqa.selenium.chromium: OFF
  file:
    name: logs/ssh-executor.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
      file-name-pattern: logs/ssh-executor-%d{yyyy-MM-dd}.%i.log.gz
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"